def build_dict(seq, key):
    return dict((d[key], dict(d, index=index)) for (index, d) in enumerate(seq))

_skillsMap = {
    0: {"category": "generic","name": "Creativity"},
    1: {"category": "generic", "name": "Interpersonal Skills"},
    2: {"category": "generic", "name": "Critical Thinking"},
    3: {"category": "generic", "name": "Problem Solving"},
    4: {"category": "generic", "name": "Public Speaking"},
    5: {"category": "generic", "name": "Customer Service Skills"},
    6: {"category": "generic", "name": "Teamwork Skills"},
    7: {"category": "generic", "name": "Communication"},
    8: {"category": "generic", "name": "Collaboration"},
    9: {"category": "generic", "name": "Accounting"},
    10: {"category": "generic", "name": "Active Listening"},
    11: {"category": "generic", "name": "Adaptability"},
    12: {"category": "generic", "name": "Negotiation"},
    13: {"category": "generic", "name": "Conflict Resolution"},
    14: {"category": "generic", "name": "Empathy"},
    15: {"category": "generic", "name": "Customer Service"},
    16: {"category": "generic", "name": "Decision Making"},
    17: {"category": "generic", "name": "Management"},
    18: {"category": "generic", "name": "Leadership skills"},
    19: {"category": "generic", "name": "Organization"},
    20: {"category": "generic", "name": "Language skills"},
    21: {"category": "generic", "name": "Administrative skills"},
    22: {"category": "practical", "name": "Construction Studies"},
    23: {"category": "practical", "name": "Engineering"},
    24: {"category": "practical", "name": "Technology"},
    25: {"category": "science", "name": "Agricultural Science"},
    26: {"category": "science", "name": "Applied Maths"},
    27: {"category": "science", "name": "Biology"},
    28: {"category": "science", "name": "Chemistry"},
    29: {"category": "science", "name": "Mathematics"},
    30: {"category": "science", "name": "Physics"},
    31: {"category": "science", "name": "Physics and Chemistry"},
    32: {"category": "science", "name": "Computer Science"},
    33: {"category": "artistic", "name": "Art"},
    34: {"category": "artistic", "name": "Music"},
    35: {"category": "artistic", "name": "Design and Comm Graphics"},
    36: {"category": "humanities", "name": "Arabic"},
    37: {"category": "humanities", "name": "Classical Studies"},
    38: {"category": "humanities", "name": "English"},
    39: {"category": "humanities", "name": "French"},
    40: {"category": "humanities", "name": "Gaeilge"},
    41: {"category": "humanities", "name": "German"},
    42: {"category": "humanities", "name": "Hebrew Studies"},
    43: {"category": "humanities", "name": "History"},
    44: {"category": "humanities", "name": "Italian"},
    45: {"category": "humanities", "name": "Japanese"},
    46: {"category": "humanities", "name": "Latin"},
    47: {"category": "humanities", "name": "Russian"},
    48: {"category": "humanities", "name": "Spanish"},
    49: {"category": "humanities", "name": "Other Language"},
    50: {"category": "humanities", "name": "Ancient Greek"},
    51: {"category": "humanities", "name": "Mandarin-Chinese"},
    52: {"category": "humanities", "name": "Polish"},
    53: {"category": "humanities", "name": "Lithuanian"},
    54: {"category": "humanities", "name": "Portuguese"},
    55: {"category": "social", "name": "Geography"},
    56: {"category": "social", "name": "Home Economics"},
    57: {"category": "social", "name": "Religious Education"},
    58: {"category": "social", "name": "Religious Education (Non Exam)"},
    59: {"category": "social", "name": "Physical Education"},
    60: {"category": "social", "name": "Politics and Society"},
    61: {"category": "business", "name": "Accounting"},
    62: {"category": "business", "name": "Business"},
    63: {"category": "business", "name": "Economics"},
    64: {"category": "business", "name": "LCVP Link Modules"},
}

#convert into an array of dict, moving the id, in the dict
skillsMap = [_skillsMap[key] for key in sorted(_skillsMap.keys())]

skills = build_dict(skillsMap, 'name')